# Generated by Django 3.0.3 on 2020-02-12 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200207_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='value',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
