# Generated by Django 3.0.3 on 2020-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
